### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by gathuaalex** [Ronnie-Leon76/PivotClubRefined#1]
Kindly update the milestones to be achieved.

**Comment by Ronnie-Leon76** [comment]
So, far I had managed to do the login, logout, signup and profile page but I think I'd like to scrap that off and use django-allauth. I promise by tomorrow I'll have made a commit. I'm working on it. I'll have the signup, signout, login, reset password and account working. So, that we can start working on the blog application to achieve CRUD. We need to enable members who have accounts to write blogs, update, delete the blogs and other things. Let me just make these changes.
